# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='button',
            name='href',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
